Python course for UIUC Physics REU 2025

Instructor: Yueying Wu

The following Python code gives an overview to scientific programming in python.

First, please make sure the code is a copy of the original.
Run all the blocks of the code once as-is.
Then follow the prompts at the bottom of the page.

* Code originally developed by Prof. Alex Sushkov for Boston University Physics 251 in 2018 based on the introduction to python by Prof. Chris Laumann, modified by Kevin Kleiner and Preethi Basani

* Rewrite the code to make sure you fully understand it

* Play with the code, change it by yourself!

# Why Python? #

### Simple, well-structured, general-purpose language
  - Readability great for quality control and collaboration
  - Code how you think: many books now use python as pseudocode
  
### High-level
  - Rapid development
  - Do complicated things in few lines

### Interactive
  - Rapid development and exploration
  - No need to compile, run, debug, revise, compile
  - Data collection, generation, analysis and publication plotting in one place

### Speed
  - With some experience in good coding, plenty fast
  - Your development time is more important than CPU time
  - Not as fast as C, C++, Fortran but these can be easily woven in where necessary

### Vibrant community
  - Great online documentation / help available
  - Open source
  
### Rich scientific computing libraries
  - Don't reinvent the wheel!


# Scientific Python Key Components #

The core pieces of the scientific Python platform are:

**[Python](http://www.python.org)**, the language interpreter
  - Many standard data types, libraries, etc
  - Python 3.6 is the current version but 2.7 is still maintained
  - Python 3 is mostly compatible with Python 2, but we will stick to 3

**[Jupyter](http://www.jupyter.org)**: notebook based (in browser) interface
  - Builds on **[IPython](http://www.ipython.org)**, the interactive Python shell
  - Interactive manipulation of plots
  - Easy to use basic parallelization
  - Lots of useful extra bells and whistles for Python
  
**[Numpy](http://www.numpy.org)**, powerful numerical array objects, and routines to manipulate them.
  - Work horse for scientific computing
  - Basic linear algebra (np.linalg)
  - Random numbers (np.random)
  
**[Scipy](http://www.scipy.org)**, high-level data processing routines.
  - Signal processing (scipy.signal)
  - Optimization (scipy.optimize)
  - Special functions (scipy.special)
  - Sparse matrices and linear algebra

**[Matplotlib](http://www.matplotlib.org)**, plotting and visualization
  - 2-D and basic 3-D interactive visualization
  - “Publication-ready” plots
  - LaTeX labels/annotations automagically




### Importing the Scientific Environment ###

The simplest way to use the basic scientific libraries (numpy, scipy) and plotting tools (matplotlib) in jupyter is to execute the following command at the beginning of your notebook:

In [ ]:
import matplotlib.pyplot as plt    

Commands beginning with % our IPython 'magic' commands. This one sets up a bunch of matplotlib back end and imports numpy into the global namespace. We will do this in all of our class notebooks. To manually import the numpy library, one could also use

In [2]:
import numpy as np

which will make all of the numpy functions, such as array() and sin(), available as np.array(), np.sin(), ...

# Jupyter Workflow #

### Two primary workflows:

1. Work in a Jupyter/IPython notebook. Write code in cells, analyze, plot, etc. Everything stored in **.ipynb** file.
2. Write code in **.py** files using a text editor and run those within the IPython notebook or from the shell.

We still stick to the first.

While you are using a notebook, there is a **kernel** running which actually executes your commands and stores your variables, etc. If you quit/restart the kernel, all variables will be forgotten and you will need to re-execute the commands that set them up. This can be useful if you want to reset things. The input and output that is visible in the notebook is saved in the notebook file.

*Note:* .py files are called **scripts** if they consist primarily of a sequence of commands to be run and **modules** if they consist primarily of function definitions for import into other scripts/notebooks.

### Notebook Usage

Two modes: editing and command mode.

Press escape to go to command mode.
Press return to go into editing mode on selected cell.

In command mode:
1. Press h for a list of keyboard commands.
2. Press a or b to create a new cell above or below the current.
3. Press m or y to convert the current cell to markdown or code.
4. Press shift-enter to execute.
5. Press d d to delete the current cell. (Careful!)

In editing mode:
1. Press tab for autocomplete
2. Press shift-tab for help on current object
3. Shift-enter to execute current cell

Two types of cells:
1. Markdown for notes (like this)
2. Code for things to execute


### Exercise ###

Try editing this markdown block to make it more interesting.

### Exercise

Execute the next block and then create a new block, type x. and press tab and shift-tab.

In [ ]:
x = 10

In [ ]:
x

10

### Exercise

Run this stuff.

In [ ]:
print('Hello, world!')

Hello, world!


In [ ]:
"Hello, world!"

'Hello, world!'

In [ ]:
2.5 * 3

7.5

In [ ]:
3**3

27

In [ ]:
3 + 3

6

In [ ]:
"ab" + "cd"

'abcd'

In [ ]:
"Hello" == 'Hello'

True

# Variables and Objects #

Everything in memory in Python is an object. Every object has a type such as int (for integer), str (for strings) or ndarray (for numpy arrays). Variables can reference objects of any type and that type can change.

The equals sign in programming does not mean 'is equal to' as in math. It means **'assign the object on the right to the variable on the left'**.


In [ ]:
a = 3

In [ ]:
a

3

In [ ]:
type(a)

int

In [ ]:
a+a

6

In [ ]:
2+a

5

In [ ]:
a = array([1,2])

In [ ]:
a

array([1, 2])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# All objects have properties, accessible with a .
a.shape

(2,)

In [ ]:
a+a

array([2, 4])

In [ ]:
2+a

array([3, 4])

In [ ]:
a = "Hello, world!"

In [ ]:
a

'Hello, world!'

In [ ]:
type(a)

str

In [ ]:
a+a

'Hello, world!Hello, world!'

In [ ]:
2+a

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### Overloading

Operators and functions will try to execute no matter what type of objects are passed to them, but they may do different things depending on the type. + adds numbers and concatenates strings.

### Variables as References ###

All variables are **references** to the objects they contain. Assignment does not make copies of objects. This is counter-intuitive for those who do not have much programming experience, so make sure you understand what this means. See code below for an illustration.

In [ ]:
a = np.array([1,2])
a

array([1, 2])

In [ ]:
b = a
b

array([1, 2])

In [ ]:
b[0] = 0
b

array([0, 2])

In [ ]:
a

array([0, 2])

# Types of Objects #

## Basic Types ##

1. **Numeric**
  1. Integer: -1, 0, 1, 2, ...
  2. Float: 1.2, 1e8
  3. Complex: 1j, 1. + 2.j
  4. Boolean: True, False
2. **Strings**, "hi"
3. Tuples, (2,7, "hi")
  - Ordered collection of other objects, represented by parentheses
  - can't change after creation (*immutable*)
3. **Lists**, [0,1,2,"hi", 4]
  - Ordered collection of other objects, represented by square brackets
  - can add/remove/change elements after creation (*mutable*)
4. Dictionaries, {'hi': 3, 4: 7, 'key': 'value'}
5. **Functions**, def func()

## Common Scientific Types ##

6. **NumPy arrays**, array([1,2,3])
  - Like lists but all entries have same type


# Basic Types: Numeric #

There are 4 numeric types:
- int: positive or negative integer
- float: a 'floating point' number is a real number like 3.1415 with a finite precision
- complex: has real and imaginary part, each of which is a float
- bool: two 'Boolean' values, True or False


In [ ]:
a = 4
type(a)

int

In [ ]:
c = 4.0
type(c)

float

In [ ]:
a = 1.5 + 0.1j
type(a)

complex

In [ ]:
a.real

1.5

In [ ]:
a.imag

0.1

In [ ]:
flag = (3>4)
flag

False

In [ ]:
type(flag)

bool

In [ ]:
type(True)

bool

In [ ]:
# Type conversion
float(1)

1.0

# Basic Types: Strings #

Strings are **immutable** sequences of characters. This means you can't change a character in the middle of a string, you have to create a new string.

Literal strings can be written with single or double-quotes. Multi-line strings with triple quotes. 'Raw' strings are useful for embedding LaTeX because they treat backslashes differently.

In [ ]:
'Hello' == "Hello"

True

In [ ]:
a = """This is a multiline string.
Nifty, huh?"""

In [ ]:
a

'This is a multiline string.\nNifty, huh?'

In [ ]:
print("\nu")


u


In [ ]:
print(r"\nu")

\nu


In [ ]:
a = 3.1415

In [ ]:
# Simple formatting (type convert to string)
"Blah " + str(a)

'Blah 3.1415'

In [ ]:
# Old style string formatting (ala sprintf in C)
"Blah %1.2f, %s" % (a, "hi")

'Blah 3.14, hi'

In [ ]:
# New style string formatting
"Blah {:1.2f}, {}".format(a, "hi")

'Blah 3.14, hi'

# Basic Types: Lists #

Python lists store **ordered** collections of arbitrary objects. They are efficient maps **from index to values**. Lists are represented by square brackets [ ].

Lists are **mutable**: their contents can be changed after they are created.

You can also grab arbitrary **slices** from a list efficiently.

Lists are 0-indexed. This means that the first item in the list is at position 0 and the
last item is at position N-1 where N is the length of the list.

In [ ]:
days_of_the_week = ["Sunday","Monday","Tuesday",
                    "Wednesday","Thursday","Friday"]

In [ ]:
days_of_the_week[0]

'Sunday'

In [ ]:
# The slice from 2 to 5 (inclusive bottom, exclusive top)
days_of_the_week[2:5]

['Tuesday', 'Wednesday', 'Thursday']

In [ ]:
days_of_the_week[-1]

'Friday'

In [ ]:
days_of_the_week[5] = "Casual Friday"

In [ ]:
days_of_the_week

['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Casual Friday']

In [ ]:
# Get the length of the list
len(days_of_the_week)

6

In [ ]:
# Sort the list in place
days_of_the_week.sort()

In [ ]:
days_of_the_week

['Casual Friday', 'Monday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']

**Remember tab completion** Every thing in Python (even the number 10) is an object. Objects can have methods which can be accessed by the notation a.method(). Typing a.<TAB> allows you to see what methods an object a supports. Try it now with days_of_the_week:


In [ ]:
days_of_the_week.extend([1])

**Each item is arbitrary**: You can have lists of lists or lists of different types of objects.

In [ ]:
aList = ["zero", 1, "two", 3., 4.+0j]
aList

['zero', 1, 'two', 3.0, (4+0j)]

In [ ]:
listOfLists = [[1,2], [3,4], [5,6,7], 'Hi']

In [ ]:
listOfLists[2][1]

6

# Numpy Arrays #

Numpy arrays store **multidimensional arrays** of objects of a fixed type. The type of an array is a **dtype**, which is a more refined typing system than Python provides. They are efficient maps **from indices (i,j) to values**. They have **minimal memory overhead**.

Arrays are **mutable**: their contents can be changed after they are created. However, their size and dtype, once created cannot be efficiently changed (requires a copy).

Arrays are good for:
1. Representing matrices and vectors (**linear algebra**)
2. Storing grids of numbers (**plotting, numerical analysis**)
3. Storing data series (**data analysis**)

Arrays are not good for:
1. Applications that require growing/shrinking the size.
2. Heterogenous objects.
3. Non-rectangular data.

Arrays are 0-indexed.

We will talk about applications 1 and 2 today.

In [ ]:
# A vector is an array with 1 index
a = np.array([1/np.sqrt(2), 0, 1/np.sqrt(2)])
a

array([0.70710678, 0.        , 0.70710678])

In [ ]:
a.shape

(3,)

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a.size

3

In [ ]:
# We access the elements using [ ]
a[0]

0.7071067811865475

In [ ]:
a[0] = a[0]*2

In [ ]:
a

array([1.41421356, 0.        , 0.70710678])

We create a 2D array (that is a matrix) by passing the array() function a list of lists of numbers in the right shape.

In [ ]:
# A matrix is an array with 2 indices
B = np.array( [[ 1, 0, 0],
            [ 0, 0, 1],
            [ 0, 1, 0]] )
B

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [ ]:
B.shape

(3, 3)

In [ ]:
B.dtype

dtype('int64')

In [ ]:
B.size

9

In [ ]:
B[0,0]

1

### Exercise ###

Change the last row of B to have a 2 instead of a 1 in the middle position.

In [ ]:
B[2][1] = 2
B

array([[1, 0, 0],
       [0, 0, 1],
       [0, 2, 0]])

**Warning!** There is also a type called 'matrix' instead of 'array' in numpy. This is specially for 2-index arrays but is being removed from Numpy over the next two years because it leads to bugs. **Never use matrix(), only array()**

## Basic Linear Algebra ##

There are two basic kinds of multiplication of arrays in Python:

1. **Element-wise multiplication:** a*b multiplies arrays of the same shape element by element.
2. **Dot product:** a@b forms a dot product of two vectors or a matrix product of two rectangular matrices.

Mathematically, for vectors,

$$ a@b = \sum_i a[i] b[i] $$

while for 2D arrays (matrices),

$$ A@B[i,j] = \sum_k A[i,k] B[k,j] $$

In [ ]:
a = np.array([2,  1])
b = np.array([3, -1])

In [ ]:
a

array([2, 1])

In [ ]:
b

array([ 3, -1])

In [ ]:
a@a

5

In [ ]:
# Compute the length of a
np.norm(a)

2.23606797749979

In [ ]:
np.sqrt(a@a)

2.23606797749979

In [ ]:
a*b

array([ 6, -1])

There are many, many more functions for doing linear algebra operations numerically provided by numpy and scipy.

# Basic Plotting #

The second primary use of numpy array's is to hold grids of numbers for analyzing and plotting. In this case, we consider a long 1D array with length N as representing the values of the x and y axis of a plot, for example.

Let's plot a sine wave:

In [ ]:
# create an equally spaced array of 100 numbers
# from -2pi to 2pi
x = np.linspace(-2*np.pi, 2*np.pi, 100)

# evaluate a function at each point in x and create a
# corresponding array
y = 0.5*np.sin(x)


plt.figure()
plt.plot(x, y)
plt.grid(True)
plt.xlabel(r'$x$')
plt.ylabel(r'$0.5 \sin(x)$')
plt.show()

<IPython.core.display.Javascript object>

Text(0, 0.5, '$0.5 \\sin(x)$')

## Some Common Arrays ##

In [ ]:
#creates a 'row vector', notice the [ ] rather than ( )
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.random.rand(2,2)

array([[0.79479409, 0.61127483],
       [0.98162114, 0.05613905]])

## Array DTypes ##

Every element in a numpy array has the same type. These are called **dtypes** because they are more specific data types than the basic python number system -- they allow you to control how many bytes are used for each number. We will typically not need to worry about this but you may need to be aware that the system is a bit different from the basic numeric types.

1. Integers: int16 ('i2'), int32 ('i4'), int64 ('i8'), ...
2. Unsigned: uint32 ('u4'), uint64 ('u8'), ...
3. Float: float16 ('f2'), float32 ('f4'), float64 ('f8'), ...
4. Boolean: bool
5. Fixed Length Strings: 'S1', 'S2', ...



In [ ]:
np.array([1,0]).dtype

dtype('int64')

In [ ]:
np.array([1.,0]).dtype

dtype('float64')

In [ ]:
np.dtype('i4')

dtype('int32')

# Control Flow #

The flow of a program is the order in which the computer executes the statements in the code. Typically, this is in order from top to bottom. However, there are many cases where we want to change the flow in some way. For example, we might want to divide two numbers but only if the divisor is not zero. Or we might want to iterate: repeat a block of code many times for each value in some list. The commands which allow these are called control flow commands.

**WARNING**: Python cares about **white space**! You must **INDENT CORRECTLY** because that's how Python knows when a block of code ends.

Typically, people indent with 4 spaces per block but 2 spaces or tabs are okay. They must be consistent in any block.

### If/elif/else

In [ ]:
if 2>3:
    print("Yep")
    print("It is")

elif 3>4:
    print("Not this one either.")

else:
    print("Not")
    print("At all")

Not
At all


### For Loops ###

For loops *iterate* through elements in a collection. This can be a list, tuple, dictionary, array or any other such collection.

These are the most *Pythonic* way to think about iterations.

In [ ]:
for i in range(5):
    j = i**3
    print("The cube of " + str(i) + " is " + str(j))

The cube of 0 is 0
The cube of 1 is 1
The cube of 2 is 8
The cube of 3 is 27
The cube of 4 is 64


In [ ]:
for day in days_of_the_week:
    print("Today is " + day)

Today is Casual Friday
Today is Monday
Today is Sunday
Today is Thursday
Today is Tuesday
Today is Wednesday


TypeError: can only concatenate str (not "int") to str

**Enumerate** to get index and value of iteration element

In [ ]:
words = ('your', 'face', 'is', 'beautiful')

for (i, word) in enumerate(words):
    print(i, word)

0 your
1 face
2 is
3 beautiful


### While Loops

Repeats a block of code while a condition holds true.

In [ ]:
x = 5

while x > 0:
    print("Bark " + str(x))
    x -= 1

Bark 5
Bark 4
Bark 3
Bark 2
Bark 1


# Functions #

Any code that you call multiple times with different values should be wrapped up in a function. For example:

In [ ]:
def square(x):
    """Return the square of x."""
    return x*x

In [ ]:
square?

In [ ]:
square(9)

81

In [ ]:
def printAndSquare(x):
    """Print the square of x and return it."""
    y = x**2
    print(y)
    return y

In [ ]:
printAndSquare?

In [ ]:
printAndSquare(8)

64


64

### Functions are Objects ###

Functions are just like any object in Python:

In [ ]:
type(square)

function

Make another variable refer to the same function:

In [ ]:
a = square

In [ ]:
a(5)

25

A function being passed to another function.

In [ ]:
def test():
    print("In Test!")
    return

def callIt(fun):
    print("In callIt!")
    fun()
    return

In [ ]:
callIt(test)

In callIt!
In Test!
